# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "polyidiot"
repo_name: "Arixv-Quantum"
show_authors: False
show_links: False
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/TQFT-arxiv-daily.json'
json_gitpage_path: './docs/TQFT-arxiv-daily-web.json'
json_wechat_path: './docs/TQFT-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Bell nonlocality": 
        filters: ["Bell nonlocality", "nonlocality", 
        "Bilocal", "Genuine nonlocality", "Bell inequality", "LHV model",
        "local hidden variable", "xor game",
        "network nonlocality",
        "GHZ paradox", 
        "EPR paradox"]
    "Quantum causal model":
        filters: ["pseudo-density operator", "pseudo-density matrix", 
        "Quantum Bayes' Rule", "Symmetric Bloom", "quantum state over time",
        "Process matrix", "Quantum Comb", "Quantum Causality", "spacetime state",
        "doubled density operator", "Leggett-Garg inequality", "quantum causal influence",
        "quantum causal modelling", "temporal quantum process", "spatiotemporal doubled density operator",
        "temporal quantum correlations", "spatiotemporal quantum correlation"]
    "Quantum contextuality":
        filters: ["Kochen-Specker contextuality","Exclusivity Principle", "no-disturbance principle",
                  "Compatibility graph", "quantum contextuality", "KCBS inequality"]
    "Quantum steering":
        filters: ["EPR steering","Quantum Steering",
                  "Steering inequality", "Temporal steering", "Genuine steering"]
    "Resource theory":
        filters: ["Quantum resource theory","Free Operation",
                  "Free state"]
    "Quantum chaos and information scrambling":
        filters: ["Quantum Chaos","Quantum Information Scrambling",
                  "Out of time order correlators", "Hayden-Preskill protocol",
                  "Entanglement spreading", "Random quantum circuit", "Loschmodt Echo"
                  ]   
    "Quantum error-correction code":
        filters: ["Quantum error-correcting code","Quantum Stabilizer Code",
                  "Surface Code", "Quantum code",
                  "Quantum Error Correcting", "Holographical Quantum Error Correction Code", "Color Code"
                  ]               
    
